### ISSUE TITLE
Recursive regex not working

### ISSUE THREAD

**Issue by VladBullet** [akashsaluja/piped-regex-vscode#1]
Hi! I was wondering what flavour of Regex does this support. 
I am using a recursive regex that matches brackets ( "{text {text} }").
The regex works in PCRE on Regexr.com
I put the regex inside double quotes here:  "\{(?:[^}{]+|(?R))*+\}" 
The way I used it with Piped Regex command: f "\{(?:[^}{]+|(?R))*+\}". 
I get this error: "Something wrong with regex".

**Comment by akashsaluja** [comment]
Hi Vlad,

I am not actively looking into the repository. But after I created the extension, I found that the same thing is possible using LookAhead feature of regex natively, and normal search/replace functionality of VSCode.

If you need help in that, let me know. I will be happy to help.

**Comment by VladBullet** [comment]
Hi! Wow! Thanks for the fast response 😄. 
I am a noob when it comes to regex. All I want is to be able to match brackets ("{text { text } }"). The only way I knew how to do that was with recursion. If you know any other way that works without recursion and with javascript flavour please share it with me :) Otherwise this issue can be closed. 😄

**Comment by akashsaluja** [comment]
If I got correctly you want to match brackets(if opening brackets are same as closing brackets and follow a semantics that opening is done before closing) using Regex? To be fair, I dont know any way to do it using regex.
